import type { BusinessAssistantConfig } from "@/components/shared/BusinessAssistantPanel"

export const companyProfileAssistant: BusinessAssistantConfig = {
  pageTitle: "Company Profile",

  about:
    "Company Profile is the tenant-level record that stores your organisation's identity, contact details, branding, and regional preferences. " +
    "Every field on this page is embedded in generated documents — invoices, purchase orders, delivery notes, work orders, and quality reports all pull from this record. " +
    "Set every field before your first transaction so that all printed and emailed documents carry accurate company information from day one.",

  businessPurpose:
    "Your GST number, company name, address, and logo appear on every invoice you send and every PO you raise. " +
    "An incorrect GST number on an invoice can cause your customers' input tax credit to be rejected. A missing logo makes your documents look unprofessional. " +
    "A wrong timezone causes transaction timestamps to show UTC instead of your local time, making it hard to reconcile records. " +
    "This page is the single source of truth for all of that — configure it once, before your first sale or purchase, and every document generated afterward will be correct.",

  erpFlow: [
    { label: "Company Profile", active: true, description: "You are here — configure before all else" },
    { label: "Number Series" },
    { label: "Unit Master" },
    { label: "Material Categories" },
    { label: "Storage Locations" },
    { label: "Materials & Products" },
    { label: "All document generation (invoices, POs, delivery notes embed logo, name, GST, address)" },
  ],

  canDo: [
    "Edit company name, GST number, and registered address",
    "Upload and preview your company logo (PNG/JPG up to 2 MB)",
    "Set contact details: phone, email",
    "Configure footer text that appears on all printed PDFs",
    "Set currency code (ISO 4217) and currency symbol for financial documents",
    "Configure timezone (IANA) so transaction timestamps use your local time",
    "Set the Default Warehouse Name label that appears on delivery notes and stock reports",
    "View a read-only version if you have Manager role",
  ],

  screenWalkthrough: [
    {
      section: "Identity section",
      purpose: "Company Name and GST Number — the two fields that appear most prominently on all official documents.",
      impact: "Company Name is required. GST Number is validated against Indian GST format if provided. Both appear on invoice headers.",
    },
    {
      section: "Contact section",
      purpose: "Address, phone, and email of your registered business.",
      impact: "Full registered address appears on invoices and purchase orders. Phone and email appear in document footers.",
    },
    {
      section: "Branding section",
      purpose: "Logo upload, footer text, and default warehouse name.",
      impact: "Logo appears as a thumbnail in the header of all printed PDFs. Footer text appears at the bottom of every printed document. Leaving logo_url blank causes all PDFs to show an empty logo space.",
    },
    {
      section: "Regional section",
      purpose: "Currency code, currency symbol, and timezone.",
      impact: "Currency code and symbol control the currency shown on financial documents. Timezone controls how all transaction timestamps are displayed — setting this to your local timezone prevents timestamps from showing in UTC.",
    },
    {
      section: "Save button",
      purpose: "Persists all changes to the company profile.",
      impact: "Changes take effect immediately. All subsequently generated documents will use the updated values. Existing saved documents are not regenerated.",
    },
    {
      section: "Read-only banner (Manager role)",
      purpose: "Managers see all fields in read-only mode with an informational banner.",
      impact: "Only ADMIN and TENANT_ADMIN can edit. Managers can view but cannot save changes.",
    },
  ],

  fieldGuide: [
    {
      field: "Company Name",
      purpose: "Your registered legal company name.",
      meaning: "Appears in the header of every invoice, PO, delivery note, and quality document generated by MedTrack.",
      example: "Acme Pharmaceuticals Pvt Ltd",
      recommended: "Required. Max 255 characters. Use your full registered legal name.",
      bestPractice: "Do not leave this as a placeholder or default value — it appears on all official documents sent to customers and suppliers.",
    },
    {
      field: "GST Number",
      purpose: "Your Goods and Services Tax registration number.",
      meaning: "Printed on every tax invoice. Customers need your GST number to claim input tax credit. Invalid format causes invoice validation to fail.",
      example: "22AAAAA0000A1Z5",
      recommended: "Optional but essential for Indian businesses. Format: 2-digit state code + 5-letter PAN + 4-digit sequence + check characters.",
      bestPractice: "Set this before your first invoice. An incorrect GST format is rejected by the system with a validation error on blur.",
    },
    {
      field: "Address",
      purpose: "Your full registered business address.",
      meaning: "Appears on invoices and purchase orders as the sender/buyer address.",
      example: "Plot 12, Industrial Area Phase 2, Pune, Maharashtra 411018",
      recommended: "Optional. Max 1000 characters. Include street, city, state, and PIN code for completeness.",
    },
    {
      field: "Phone",
      purpose: "Primary contact phone number for your business.",
      meaning: "Printed in document footers and used by suppliers and customers to contact your team.",
      example: "+91 98765 43210",
      recommended: "Optional. Max 50 characters.",
    },
    {
      field: "Email",
      purpose: "Primary contact email address.",
      meaning: "Appears in document footers. Validated as a proper email format if provided.",
      example: "accounts@acmepharma.in",
      recommended: "Optional. Must be valid email format if provided.",
    },
    {
      field: "Logo",
      purpose: "Your company logo image for document headers.",
      meaning: "Embedded as a thumbnail in the header of all PDF documents generated by MedTrack.",
      example: "PNG or JPG file, max 2 MB",
      recommended: "PNG or JPG only. Max 2 MB. Leaving this blank causes all PDFs to show an empty logo placeholder.",
      bestPractice: "Use a high-contrast logo on a transparent or white background. Recommended dimensions: 200×80 px or wider.",
    },
    {
      field: "Footer Text",
      purpose: "Custom text printed at the bottom of all PDF documents.",
      meaning: "Commonly used for legal disclaimers, bank details, or 'Thank you for your business' messages.",
      example: "Bank: HDFC Bank | A/C: 50100123456789 | IFSC: HDFC0001234 | Thank you for your business!",
      recommended: "Optional. Max 500 characters.",
    },
    {
      field: "Currency Code",
      purpose: "ISO 4217 currency code for all financial documents.",
      meaning: "Determines which currency symbol and code appears on invoices, POs, and financial reports.",
      example: "INR (Indian Rupee), USD (US Dollar), EUR (Euro)",
      recommended: "Optional but important. Select from the ISO 4217 dropdown. Default is system-level if not set.",
      bestPractice: "Set this before any purchase orders or invoices are created so all financial documents use the correct currency.",
    },
    {
      field: "Currency Symbol",
      purpose: "The symbol displayed alongside amounts in documents and the UI.",
      meaning: "Shown before or after monetary amounts in invoices, reports, and the ERP dashboard.",
      example: "₹ for INR, $ for USD, € for EUR",
      recommended: "Optional. Usually auto-populated when you select Currency Code.",
    },
    {
      field: "Timezone",
      purpose: "IANA timezone string for your business location.",
      meaning: "All transaction timestamps in MedTrack are stored in UTC internally and displayed in this timezone. Without it, timestamps show in UTC.",
      example: "Asia/Kolkata, Asia/Dubai, UTC, America/New_York",
      recommended: "Optional but strongly recommended. Select via the searchable IANA timezone dropdown.",
      bestPractice: "Set this before your first transaction. Changing timezone after transactions exist does not retroactively update existing timestamps.",
    },
    {
      field: "Default Warehouse Name",
      purpose: "A text label for your single warehouse facility.",
      meaning: "This label appears on delivery notes, stock reports, and any document that references your warehouse. It is a display label only — not a warehouse FK.",
      example: "Main Facility, Pune Plant, Distribution Centre",
      recommended: "Optional. Max 100 characters.",
    },
  ],

  buttonGuide: [
    {
      button: "Save",
      what: "Persists all edited fields to the company profile record.",
      continues: "Success toast confirms the save. All subsequent document generation uses the updated values immediately.",
      reversible: true,
    },
    {
      button: "Upload Logo",
      what: "Drag-and-drop or click to select a PNG/JPG file (max 2 MB).",
      continues: "File is uploaded to the file service; the returned URL is stored as logo_url. A thumbnail preview is shown immediately after upload.",
      reversible: true,
    },
    {
      button: "Remove Logo",
      what: "Clears the current logo_url from the form state.",
      continues: "After saving, all PDFs will show a blank logo area. Upload a new logo to restore branding.",
      reversible: true,
    },
  ],

  beforeYouStart: [
    "You have ADMIN or TENANT_ADMIN role — Managers see a read-only view",
    "You have your company's GST certificate with the correct GST number",
    "You have the company logo file (PNG or JPG, ideally with white/transparent background)",
    "You know your company's IANA timezone (e.g. Asia/Kolkata for India)",
    "You know your currency code (e.g. INR for India)",
    "Configure this page before creating any materials, products, or transactions",
  ],

  afterSave: [
    { label: "Profile saved" },
    { label: "Audit log entry recorded (old and new values)" },
    { label: "All new invoices use updated company name, GST, address, logo" },
    { label: "All new POs use updated company details" },
    { label: "All new delivery notes use updated address and warehouse name" },
    { label: "Timestamps displayed in configured timezone" },
  ],

  bestPractices: [
    "Configure this page as the very first step — before Number Series, before master data, before any transaction",
    "Set GST number before your first invoice — it appears on every tax invoice and customers need it for ITC",
    "Upload the logo before generating any PDFs — blank logo on all documents is hard to recover gracefully",
    "Set timezone to your local IANA timezone — all transaction timestamps will display in local time",
    "Set currency code to INR (or your local currency) before any PO or invoice is created",
    "Review document footer text with your finance team — bank details in the footer save manual work on every invoice",
  ],

  commonMistakes: [
    "Leaving logo_url blank — all PDFs will show an empty logo space; upload logo before going live",
    "Entering wrong GST format — MedTrack validates the Indian GST pattern on blur; an incorrect format blocks saving",
    "Not setting timezone — all transaction timestamps show in UTC instead of your local time, making it impossible to match records to business hours",
    "Not setting currency_code — financial reports may use wrong or missing currency symbol",
    "Leaving company_name as a placeholder or default — this name appears on every document sent to customers and suppliers",
    "Uploading a logo larger than 2 MB — the upload is rejected client-side with an inline error",
  ],

  relatedScreens: [
    { label: "Number Series", href: "/settings/business-config/number-series" },
    { label: "Unit Master", href: "/settings/master-data/units" },
    { label: "Material Categories", href: "/settings/master-data/categories" },
    { label: "Storage Locations", href: "/settings/master-data/locations" },
  ],

  faqs: [
    {
      question: "Which documents use the company profile fields?",
      answer: "Every document generated by MedTrack embeds company profile data: Tax Invoices (company_name, GST, address, logo), Purchase Orders (company_name, address, GST), Delivery Notes (company_name, address, default_warehouse_name), Quality Reports (company_name, logo), and Work Orders (company_name). Footer text appears on all printed PDFs.",
    },
    {
      question: "What is the correct Indian GST number format?",
      answer: "The format is: 2-digit state code + 5-letter PAN characters + 4-digit entity number + 1 letter + 1 alphanumeric + Z + 1 alphanumeric. Example: 22AAAAA0000A1Z5. The system validates this pattern on blur — an incorrect format shows an inline error and blocks saving.",
    },
    {
      question: "Why does timezone matter if I am in a single country?",
      answer: "MedTrack stores all timestamps internally in UTC. Without a configured timezone, the UI and printed documents display timestamps in UTC. For an Indian business, a GRN received at 10:00 AM IST would appear as 04:30 AM UTC — confusing for audits and shift reports. Setting Asia/Kolkata converts all displayed times to IST.",
    },
    {
      question: "Can a Manager edit the company profile?",
      answer: "No. Managers see a read-only view of the company profile with an informational banner. Only ADMIN and TENANT_ADMIN roles can save changes.",
    },
    {
      question: "Does saving the profile update documents already generated?",
      answer: "No. Existing saved or printed documents are not regenerated. The updated values are only used for documents generated after the save. This is by design — historical documents must remain as-issued.",
    },
    {
      question: "What file formats are accepted for the logo?",
      answer: "PNG and JPG only. Maximum file size is 2 MB. Files larger than 2 MB or in other formats (GIF, SVG, PDF) are rejected client-side with an inline error message before any upload attempt.",
    },
  ],

  tips: [
    "GST number is printed on every invoice — set it before your first sale, not after",
    "Logo appears on all printed PDFs — upload it during initial setup so your very first invoice looks professional",
    "The footer text field is perfect for bank account details — saves adding them manually to every invoice",
    "Use the timezone searchable dropdown to quickly find your city (e.g. type 'Kolkata', 'Dubai', 'London')",
    "Currency Code and Currency Symbol are separate fields — Currency Code (INR) is used for ISO compliance, Currency Symbol (₹) is used for display",
  ],

  warnings: [
    "Only ADMIN and TENANT_ADMIN can edit — Managers see a read-only view",
    "An incorrect GST number format is validated on blur and blocks saving — double-check before entering",
    "Changing timezone does not retroactively update already-saved transaction timestamps — set it before your first transaction",
    "Logo files must be PNG or JPG and under 2 MB — other formats and oversized files are rejected",
  ],

  successResult: [
    "Company name, GST number, and address are correctly set",
    "Logo is uploaded and visible in the preview thumbnail",
    "Timezone is set to your local IANA timezone",
    "Currency code and symbol match your operating currency",
    "Footer text is configured with bank details or standard disclaimer",
    "Save toast confirms the profile was persisted",
    "Audit log shows the save with old and new field values",
    "The next invoice or PO generated embeds the correct company details",
  ],
}
